name: gym-retention-environment
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - xgboost
  - statsmodels=0.14.2
  - pip:
      - nbgitpuller
      - sphinx-gallery